### ISSUE TITLE
Http 请求出错 

### ISSUE THREAD

**Issue by zhuzhichao** [ElfSundae/laravel-bearychat#1]
有个问题, 错误日志如下, 麻烦帮忙看看什么问题

项目用的 GuzzleHttp :  "guzzlehttp/guzzle": "^6.2"

> Exception when processing App\Jobs\SendBearyChat
> GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187
> Stack trace:
> # 0 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
> # 1 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> # 2 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> # 3 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> # 4 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> # 5 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(72): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> # 6 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> # 7 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> # 8 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> # 9 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> # 10 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Client.php(268): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> # 11 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
> # 12 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync('post', Object(GuzzleHttp\Psr7\Uri), Array)
> # 13 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('post', NULL, Array)
> # 14 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/elfsundae/bearychat/src/Client.php(156): GuzzleHttp\Client->__call('post', Array)
> # 15 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/elfsundae/bearychat/src/Message.php(580): ElfSundae\BearyChat\Client->sendMessage(Object(ElfSundae\BearyChat\Message))
> # 16 /Users/zhuzhichao/Sites/fangxin/FX-ERP/app/Jobs/SendBearyChat.php(39): ElfSundae\BearyChat\Message->send()
> # 17 [internal function]: App\Jobs\SendBearyChat->handle()
> # 18 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
> # 19 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(82): Illuminate\Container\Container->call(Array)
> # 20 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus{closure}(Object(App\Jobs\SendBearyChat))
> # 21 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(150): call_user_func(Object(Closure), Object(App\Jobs\SendBearyChat))
> # 22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(App\Jobs\SendBearyChat))
> # 23 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(App\Jobs\SendBearyChat))
> # 24 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(83): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> # 25 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(41): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\SendBearyChat))
> # 26 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(130): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
> # 27 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Queue/Jobs/SyncJob.php(44): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
> # 28 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(30): Illuminate\Queue\Jobs\SyncJob->fire()
> # 29 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(143): Illuminate\Queue\SyncQueue->push(Object(App\Jobs\SendBearyChat))
> # 30 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(118): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\SyncQueue), Object(App\Jobs\SendBearyChat))
> # 31 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(67): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(App\Jobs\SendBearyChat))
> # 32 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(323): Illuminate\Bus\Dispatcher->dispatch(Object(App\Jobs\SendBearyChat))
> # 33 /Users/zhuzhichao/Sites/fangxin/FX-ERP/app/Exceptions/Handler.php(65): dispatch(Object(App\Jobs\SendBearyChat))
> # 34 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(80): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
> # 35 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(56): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
> # 36 /Users/zhuzhichao/Sites/fangxin/FX-ERP/app/Http/Middleware/VerifyCsrfToken.php(34): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
> # 37 [internal function]: App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
> # 38 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
> # 39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
> # 40 /Users/zhuzhichao/Sites/fangxin/FX-ERP/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure)

**Comment by zhuzhichao** [comment]
自己的问题, 谢谢这么好的工具

**Comment by ElfSundae** [comment]
这个错误一般是请求的 URL 不正确，你是不是没配置 webhook ？看下 readme 里的集成文档。

另外，1.0 和 1.1 的配置文件稍有变化，是不是升级导致的错误？参考下 CHANGLOG

## Best Regards,

Elf Sundae
http://0x123.com

**Comment by ElfSundae** [comment]
OK����������������������������������������������
