### ISSUE TITLE
Fatal error: Uncaught exception 'ErrorException' with message 'Argument 1 passed to 

### ISSUE THREAD

**Issue by SIRzhou** [ElfSundae/laravel-bearychat#3]
Fatal error: Uncaught exception 'ErrorException' with message 'Argument 1 passed to ElfSundae\BearyChat\Laravel\ClientManager::__construct() must be an instance of Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given, called in D:\phpStudy\WWW\abc\poker_php\vendor\elfsundae\laravel-bearychat\src\ServiceProvider.php on line 66 and defined' in D:\phpStudy\WWW\abc\poker_php\vendor\elfsundae\laravel-bearychat\src\ClientManager.php:44 Stack trace: #0 D:\phpStudy\WWW\abc\poker_php\vendor\elfsundae\laravel-bearychat\src\ClientManager.php(44): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(4096, 'Argument 1 pass...', 'D:\\phpStudy\\WWW...', 44, Array) #1 D:\phpStudy\WWW\abc\poker_php\vendor\elfsundae\laravel-bearychat\src\ServiceProvider.php(66): ElfSundae\BearyChat\Laravel\ClientManager->__construct(Object(Laravel\Lumen\Application)) #2 D:\phpStudy\WWW\abc\poker_php\vendor\illuminate\container\Container.php(731): ElfSundae\BearyChat\Laravel\ServiceProvider->ElfSundae\BearyChat\Lar in D:\phpStudy\WWW\abc\poker_php\vendor\elfsundae\laravel-bearychat\src\ClientManager.php on line 44

**Comment by ElfSundae** [comment]
@SIRzhou 好了？
