### ISSUE TITLE
Fatal error: Uncaught exception 'ErrorException' with message 'Argument 1 passed to 

### ISSUE THREAD

**Issue by SIRzhou** [ElfSundae/laravel-bearychat#4]
ElfSundae\BearyChat\Laravel\ClientManager::__construct() must be an instance of Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given, called in D:\phpStudy\WWW\abc\poker_php\vendor\elfsundae\laravel-bearychat\src\ServiceProvider.php on line 66 and defined' in D:\phpStudy\WWW\abc\poker_php\vendor\elfsundae\laravel-bearychat\src\ClientManager.php:44 Stack trace: #0 D:\phpStudy\WWW\abc\poker_php\vendor\elfsundae\laravel-bearychat\src\ClientManager.php(44): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(4096, 'Argument 1 pass...', 'D:\\phpStudy\\WWW...', 44, Array) #1 D:\phpStudy\WWW\abc\poker_php\vendor\elfsundae\laravel-bearychat\src\ServiceProvider.php(66): ElfSundae\BearyChat\Laravel\ClientManager->__construct(Object(Laravel\Lumen\Application)) #2 D:\phpStudy\WWW\abc\poker_php\vendor\illuminate\container\Container.php(731): ElfSundae\BearyChat\Laravel\ServiceProvider->ElfSundae\BearyChat\Lar in

**Comment by ElfSundae** [comment]
Lumen 版本多少

**Comment by SIRzhou** [comment]
5.2

**Comment by SIRzhou** [comment]
感觉好像门面那出了问题

**Comment by ElfSundae** [comment]
查出来了，稍后发布新版本

**Comment by SIRzhou** [comment]
好的，能告诉我是为什么吗

**Comment by ElfSundae** [comment]
已发布 v1.1.4， 执行 `composer update` 更新下版本就正常了。
