### ISSUE TITLE
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 3:

### ISSUE THREAD

**Issue by SIRzhou** [ElfSundae/laravel-bearychat#6]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /home/wwwroot/poker_zhouyu/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187 Stack trace: #0 /home/wwwroot/poker_zhouyu/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /home/wwwroot/poker_zhouyu/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /home/wwwroot/poker_zhouyu/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 /home/wwwroot/poker_zhouyu/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): G in /home/wwwroot/poker_zhouyu/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187
这是怎么回事呢

**Comment by ElfSundae** [comment]
`config/bearychat.php` 里的 `webhook` 地址可能没有配置或者写错了，[参考文档](https://github.com/ElfSundae/Laravel-BearyChat/blob/master/README_zh.md)检查下。

如果配置是正确的，把地址换成 http 协议，可能是你本地环境的 ssl 安装有问题。

**Comment by SIRzhou** [comment]
'clients' => [

        'default' => [
            'webhook' => 'http://hook.bearychat.com/=bw929/incoming/9c78a5a6dcd3342b3d7dc42207d74de7',
             'message_defaults' => [
                 'attachment_color' => '#f5f5f5',
             ],
        ],
    ],
这配置文件，换成http还是报错

**Comment by SIRzhou** [comment]
好了，解决了，谢谢
